name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: cache .npm
        uses: actions/cache@v2
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Clean Install
        continue-on-error: true
        run: |
          npm clean-install

      - name: Clean Install Again
        # run install twice for reasons
        continue-on-error: true
        run: |
          npm clean-install

      - run: npm run clean-build

      - run: npm run lint
